- name: "Installing additional software"
  apt: pkg={{ item }} state=installed
  with_items:
  - dnsutils
  - git
  - vim
  - ntp
  - at

- name: "Adding bashrc"
  copy: src=../files/bash.bashrc dest=/etc/bash.bashrc owner=root group=root mode=0644

- name: "Removing Richard's bashrc"
  shell: creates=/home/richard/.bashrc_backup mv /home/richard/.bashrc /home/richard/.bashrc_backup

- name: "root's bashrc"
  shell: creates=/root/.bashrc_backup mv /root/.bashrc /root/.bashrc_backup
